// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.3
// source: stores.proto

package foodpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Food struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName    string `protobuf:"bytes,1,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Vegetarian  bool   `protobuf:"varint,3,opt,name=vegetarian,proto3" json:"vegetarian,omitempty"`
	Price       int64  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Cuisine     string `protobuf:"bytes,5,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
}

func (x *Food) Reset() {
	*x = Food{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Food) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Food) GetVegetarian() bool {
	if x != nil {
		return x.Vegetarian
	}
	return false
}

func (x *Food) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Food) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

type CreateStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreName   string `protobuf:"bytes,1,opt,name=storeName,proto3" json:"storeName,omitempty"`
	Street      string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	State       string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country     string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	PhoneNumber string `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Pincode     int64  `protobuf:"varint,7,opt,name=pincode,proto3" json:"pincode,omitempty"`
	UserID      string `protobuf:"bytes,8,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *CreateStoreRequest) Reset() {
	*x = CreateStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreRequest) ProtoMessage() {}

func (x *CreateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStoreRequest) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *CreateStoreRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateStoreRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateStoreRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateStoreRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateStoreRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStoreRequest) GetPincode() int64 {
	if x != nil {
		return x.Pincode
	}
	return 0
}

func (x *CreateStoreRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID    string              `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	AddedStore *CreateStoreRequest `protobuf:"bytes,2,opt,name=addedStore,proto3" json:"addedStore,omitempty"`
}

func (x *CreateStoreResponse) Reset() {
	*x = CreateStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreResponse) ProtoMessage() {}

func (x *CreateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreResponse.ProtoReflect.Descriptor instead.
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStoreResponse) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *CreateStoreResponse) GetAddedStore() *CreateStoreRequest {
	if x != nil {
		return x.AddedStore
	}
	return nil
}

type ExploreOutletsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ExploreOutletsRequest) Reset() {
	*x = ExploreOutletsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploreOutletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploreOutletsRequest) ProtoMessage() {}

func (x *ExploreOutletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploreOutletsRequest.ProtoReflect.Descriptor instead.
func (*ExploreOutletsRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{3}
}

func (x *ExploreOutletsRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ExporeOutletsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreName   string `protobuf:"bytes,1,opt,name=storeName,proto3" json:"storeName,omitempty"`
	Street      string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	State       string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StoreID     string `protobuf:"bytes,5,opt,name=storeID,proto3" json:"storeID,omitempty"`
}

func (x *ExporeOutletsResponse) Reset() {
	*x = ExporeOutletsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExporeOutletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExporeOutletsResponse) ProtoMessage() {}

func (x *ExporeOutletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExporeOutletsResponse.ProtoReflect.Descriptor instead.
func (*ExporeOutletsResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{4}
}

func (x *ExporeOutletsResponse) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *ExporeOutletsResponse) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ExporeOutletsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ExporeOutletsResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExporeOutletsResponse) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

type OrderFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID  string `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	StoreID string `protobuf:"bytes,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
}

func (x *OrderFoodRequest) Reset() {
	*x = OrderFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFoodRequest) ProtoMessage() {}

func (x *OrderFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFoodRequest.ProtoReflect.Descriptor instead.
func (*OrderFoodRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{5}
}

func (x *OrderFoodRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *OrderFoodRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

type OrderFoodRespomse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryTime        string `protobuf:"bytes,1,opt,name=deliveryTime,proto3" json:"deliveryTime,omitempty"`
	ItemName            string `protobuf:"bytes,8,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Price               int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	CustomerHouseNo     string `protobuf:"bytes,3,opt,name=customerHouseNo,proto3" json:"customerHouseNo,omitempty"`
	CustomerStreet      string `protobuf:"bytes,4,opt,name=customerStreet,proto3" json:"customerStreet,omitempty"`
	CutomerState        string `protobuf:"bytes,5,opt,name=cutomerState,proto3" json:"cutomerState,omitempty"`
	CustomerPhoneNumber string `protobuf:"bytes,6,opt,name=customerPhoneNumber,proto3" json:"customerPhoneNumber,omitempty"`
	Pincode             int64  `protobuf:"varint,7,opt,name=pincode,proto3" json:"pincode,omitempty"`
}

func (x *OrderFoodRespomse) Reset() {
	*x = OrderFoodRespomse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFoodRespomse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFoodRespomse) ProtoMessage() {}

func (x *OrderFoodRespomse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFoodRespomse.ProtoReflect.Descriptor instead.
func (*OrderFoodRespomse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{6}
}

func (x *OrderFoodRespomse) GetDeliveryTime() string {
	if x != nil {
		return x.DeliveryTime
	}
	return ""
}

func (x *OrderFoodRespomse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *OrderFoodRespomse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderFoodRespomse) GetCustomerHouseNo() string {
	if x != nil {
		return x.CustomerHouseNo
	}
	return ""
}

func (x *OrderFoodRespomse) GetCustomerStreet() string {
	if x != nil {
		return x.CustomerStreet
	}
	return ""
}

func (x *OrderFoodRespomse) GetCutomerState() string {
	if x != nil {
		return x.CutomerState
	}
	return ""
}

func (x *OrderFoodRespomse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *OrderFoodRespomse) GetPincode() int64 {
	if x != nil {
		return x.Pincode
	}
	return 0
}

type AddItemsInStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details *Food  `protobuf:"bytes,1,opt,name=Details,proto3" json:"Details,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	StoreID string `protobuf:"bytes,3,opt,name=storeID,proto3" json:"storeID,omitempty"`
}

func (x *AddItemsInStoreRequest) Reset() {
	*x = AddItemsInStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemsInStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemsInStoreRequest) ProtoMessage() {}

func (x *AddItemsInStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemsInStoreRequest.ProtoReflect.Descriptor instead.
func (*AddItemsInStoreRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{7}
}

func (x *AddItemsInStoreRequest) GetDetails() *Food {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AddItemsInStoreRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AddItemsInStoreRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

type AddItemsInStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddItemsInStoreResponse) Reset() {
	*x = AddItemsInStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemsInStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemsInStoreResponse) ProtoMessage() {}

func (x *AddItemsInStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemsInStoreResponse.ProtoReflect.Descriptor instead.
func (*AddItemsInStoreResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{8}
}

func (x *AddItemsInStoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FilterFoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price      int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Cuisine    string `protobuf:"bytes,3,opt,name=cuisine,proto3" json:"cuisine,omitempty"`
	Vegetarian bool   `protobuf:"varint,4,opt,name=vegetarian,proto3" json:"vegetarian,omitempty"`
	Name       string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	StoreID    string `protobuf:"bytes,6,opt,name=storeID,proto3" json:"storeID,omitempty"`
}

func (x *FilterFoodRequest) Reset() {
	*x = FilterFoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterFoodRequest) ProtoMessage() {}

func (x *FilterFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterFoodRequest.ProtoReflect.Descriptor instead.
func (*FilterFoodRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{9}
}

func (x *FilterFoodRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FilterFoodRequest) GetCuisine() string {
	if x != nil {
		return x.Cuisine
	}
	return ""
}

func (x *FilterFoodRequest) GetVegetarian() bool {
	if x != nil {
		return x.Vegetarian
	}
	return false
}

func (x *FilterFoodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterFoodRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

type FilterFoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filtered *Food `protobuf:"bytes,1,opt,name=filtered,proto3" json:"filtered,omitempty"`
}

func (x *FilterFoodResponse) Reset() {
	*x = FilterFoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterFoodResponse) ProtoMessage() {}

func (x *FilterFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterFoodResponse.ProtoReflect.Descriptor instead.
func (*FilterFoodResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{10}
}

func (x *FilterFoodResponse) GetFiltered() *Food {
	if x != nil {
		return x.Filtered
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID           string                  `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	StoreID          string                  `protobuf:"bytes,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
	UserID           string                  `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	UpdateItemDetail *AddItemsInStoreRequest `protobuf:"bytes,4,opt,name=UpdateItemDetail,proto3" json:"UpdateItemDetail,omitempty"`
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *UpdateItemRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *UpdateItemRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpdateItemRequest) GetUpdateItemDetail() *AddItemsInStoreRequest {
	if x != nil {
		return x.UpdateItemDetail
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateItemDetail *AddItemsInStoreResponse `protobuf:"bytes,1,opt,name=UpdateItemDetail,proto3" json:"UpdateItemDetail,omitempty"`
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateItemResponse) GetUpdateItemDetail() *AddItemsInStoreResponse {
	if x != nil {
		return x.UpdateItemDetail
	}
	return nil
}

type UpdateStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID        string              `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	UpdatedDetails *CreateStoreRequest `protobuf:"bytes,2,opt,name=updatedDetails,proto3" json:"updatedDetails,omitempty"`
}

func (x *UpdateStoreRequest) Reset() {
	*x = UpdateStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreRequest) ProtoMessage() {}

func (x *UpdateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateStoreRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateStoreRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *UpdateStoreRequest) GetUpdatedDetails() *CreateStoreRequest {
	if x != nil {
		return x.UpdatedDetails
	}
	return nil
}

type UpdateStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedDetails *CreateStoreResponse `protobuf:"bytes,1,opt,name=updatedDetails,proto3" json:"updatedDetails,omitempty"`
}

func (x *UpdateStoreResponse) Reset() {
	*x = UpdateStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStoreResponse) ProtoMessage() {}

func (x *UpdateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateStoreResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStoreResponse) GetUpdatedDetails() *CreateStoreResponse {
	if x != nil {
		return x.UpdatedDetails
	}
	return nil
}

type DeleteStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID string `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	UserID  string `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *DeleteStoreRequest) Reset() {
	*x = DeleteStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreRequest) ProtoMessage() {}

func (x *DeleteStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteStoreRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *DeleteStoreRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteStoreResponse) Reset() {
	*x = DeleteStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreResponse) ProtoMessage() {}

func (x *DeleteStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteStoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID  string `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	StoreID string `protobuf:"bytes,2,opt,name=storeID,proto3" json:"storeID,omitempty"`
	UserID  string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteItemRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *DeleteItemRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *DeleteItemRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ViewParticularStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID string `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
}

func (x *ViewParticularStoreRequest) Reset() {
	*x = ViewParticularStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewParticularStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewParticularStoreRequest) ProtoMessage() {}

func (x *ViewParticularStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewParticularStoreRequest.ProtoReflect.Descriptor instead.
func (*ViewParticularStoreRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{19}
}

func (x *ViewParticularStoreRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

type ViewParticularStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID string `protobuf:"bytes,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Foods  *Food  `protobuf:"bytes,2,opt,name=foods,proto3" json:"foods,omitempty"`
}

func (x *ViewParticularStoreResponse) Reset() {
	*x = ViewParticularStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewParticularStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewParticularStoreResponse) ProtoMessage() {}

func (x *ViewParticularStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewParticularStoreResponse.ProtoReflect.Descriptor instead.
func (*ViewParticularStoreResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{20}
}

func (x *ViewParticularStoreResponse) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

func (x *ViewParticularStoreResponse) GetFoods() *Food {
	if x != nil {
		return x.Foods
	}
	return nil
}

type GetItemDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID string `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	ItemID  string `protobuf:"bytes,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
}

func (x *GetItemDetailsRequest) Reset() {
	*x = GetItemDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDetailsRequest) ProtoMessage() {}

func (x *GetItemDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetItemDetailsRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{21}
}

func (x *GetItemDetailsRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *GetItemDetailsRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

type GetItemDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details *Food `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *GetItemDetailsResponse) Reset() {
	*x = GetItemDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemDetailsResponse) ProtoMessage() {}

func (x *GetItemDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetItemDetailsResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{22}
}

func (x *GetItemDetailsResponse) GetDetails() *Food {
	if x != nil {
		return x.Details
	}
	return nil
}

type CheckOutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreID string `protobuf:"bytes,1,opt,name=storeID,proto3" json:"storeID,omitempty"`
	ItemID  string `protobuf:"bytes,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{23}
}

func (x *CheckOutRequest) GetStoreID() string {
	if x != nil {
		return x.StoreID
	}
	return ""
}

func (x *CheckOutRequest) GetItemID() string {
	if x != nil {
		return x.ItemID
	}
	return ""
}

type CheckOutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName     string `protobuf:"bytes,1,opt,name=ItemName,proto3" json:"ItemName,omitempty"`
	Price        int64  `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	DeliveryTime string `protobuf:"bytes,3,opt,name=deliveryTime,proto3" json:"deliveryTime,omitempty"`
}

func (x *CheckOutResponse) Reset() {
	*x = CheckOutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stores_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutResponse) ProtoMessage() {}

func (x *CheckOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stores_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutResponse.ProtoReflect.Descriptor instead.
func (*CheckOutResponse) Descriptor() ([]byte, []int) {
	return file_stores_proto_rawDescGZIP(), []int{24}
}

func (x *CheckOutResponse) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *CheckOutResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CheckOutResponse) GetDeliveryTime() string {
	if x != nil {
		return x.DeliveryTime
	}
	return ""
}

var File_stores_proto protoreflect.FileDescriptor

var file_stores_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x65, 0x67, 0x65, 0x74, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x76, 0x65, 0x67, 0x65, 0x74, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x22, 0xf0, 0x01,
	0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x70, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x22, 0x6b, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x44, 0x12, 0x3a, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x31, 0x0a,
	0x15, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x6c, 0x65, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x9f, 0x01, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x6c, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x22, 0x44, 0x0a, 0x10, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x22, 0xab, 0x02, 0x0a, 0x11, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6d, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x12, 0x26,
	0x0a, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x75, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70,
	0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x72, 0x0a, 0x16, 0x61, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x52,
	0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x22, 0x33, 0x0a, 0x17, 0x61, 0x64,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x91, 0x01, 0x0a, 0x11, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75,
	0x69, 0x73, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x67, 0x65, 0x74, 0x61, 0x72,
	0x69, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x76, 0x65, 0x67, 0x65, 0x74,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x12, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x4a, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49,
	0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0x61, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x49, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0x72, 0x0a, 0x12, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x12, 0x42, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x73, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x5a, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x13, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5d, 0x0a, 0x11, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x12, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x1a, 0x76, 0x69,
	0x65, 0x77, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x44, 0x22, 0x59, 0x0a, 0x1b, 0x76, 0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x75, 0x6c, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x05, 0x66, 0x6f, 0x6f,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x49, 0x0a,
	0x15, 0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22, 0x40, 0x0a, 0x16, 0x67, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x66, 0x6f, 0x6f,
	0x64, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x43, 0x0a, 0x0f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x22,
	0x68, 0x0a, 0x10, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x8b, 0x07, 0x0a, 0x0d, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x73, 0x2e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x12, 0x1d,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x4f,
	0x75, 0x74, 0x6c, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x65, 0x4f, 0x75, 0x74,
	0x6c, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x40,
	0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x18, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6d, 0x73, 0x65,
	0x12, 0x4d, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x49, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x44, 0x69, 0x73, 0x68, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x4a, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x61, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x49, 0x6e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x56, 0x69,
	0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x4f, 0x66, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x22, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x76, 0x69, 0x65, 0x77, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x75, 0x6c, 0x61, 0x72, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x2e, 0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x67, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x66, 0x6f, 0x6f,
	0x64, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stores_proto_rawDescOnce sync.Once
	file_stores_proto_rawDescData = file_stores_proto_rawDesc
)

func file_stores_proto_rawDescGZIP() []byte {
	file_stores_proto_rawDescOnce.Do(func() {
		file_stores_proto_rawDescData = protoimpl.X.CompressGZIP(file_stores_proto_rawDescData)
	})
	return file_stores_proto_rawDescData
}

var file_stores_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_stores_proto_goTypes = []interface{}{
	(*Food)(nil),                        // 0: stores.food
	(*CreateStoreRequest)(nil),          // 1: stores.createStoreRequest
	(*CreateStoreResponse)(nil),         // 2: stores.createStoreResponse
	(*ExploreOutletsRequest)(nil),       // 3: stores.exploreOutletsRequest
	(*ExporeOutletsResponse)(nil),       // 4: stores.exporeOutletsResponse
	(*OrderFoodRequest)(nil),            // 5: stores.orderFoodRequest
	(*OrderFoodRespomse)(nil),           // 6: stores.orderFoodRespomse
	(*AddItemsInStoreRequest)(nil),      // 7: stores.addItemsInStoreRequest
	(*AddItemsInStoreResponse)(nil),     // 8: stores.addItemsInStoreResponse
	(*FilterFoodRequest)(nil),           // 9: stores.filterFoodRequest
	(*FilterFoodResponse)(nil),          // 10: stores.filterFoodResponse
	(*UpdateItemRequest)(nil),           // 11: stores.updateItemRequest
	(*UpdateItemResponse)(nil),          // 12: stores.updateItemResponse
	(*UpdateStoreRequest)(nil),          // 13: stores.updateStoreRequest
	(*UpdateStoreResponse)(nil),         // 14: stores.updateStoreResponse
	(*DeleteStoreRequest)(nil),          // 15: stores.deleteStoreRequest
	(*DeleteStoreResponse)(nil),         // 16: stores.deleteStoreResponse
	(*DeleteItemRequest)(nil),           // 17: stores.deleteItemRequest
	(*DeleteItemResponse)(nil),          // 18: stores.deleteItemResponse
	(*ViewParticularStoreRequest)(nil),  // 19: stores.viewParticularStoreRequest
	(*ViewParticularStoreResponse)(nil), // 20: stores.viewParticularStoreResponse
	(*GetItemDetailsRequest)(nil),       // 21: stores.getItemDetailsRequest
	(*GetItemDetailsResponse)(nil),      // 22: stores.getItemDetailsResponse
	(*CheckOutRequest)(nil),             // 23: stores.checkOutRequest
	(*CheckOutResponse)(nil),            // 24: stores.checkOutResponse
}
var file_stores_proto_depIdxs = []int32{
	1,  // 0: stores.createStoreResponse.addedStore:type_name -> stores.createStoreRequest
	0,  // 1: stores.addItemsInStoreRequest.Details:type_name -> stores.food
	0,  // 2: stores.filterFoodResponse.filtered:type_name -> stores.food
	7,  // 3: stores.updateItemRequest.UpdateItemDetail:type_name -> stores.addItemsInStoreRequest
	8,  // 4: stores.updateItemResponse.UpdateItemDetail:type_name -> stores.addItemsInStoreResponse
	1,  // 5: stores.updateStoreRequest.updatedDetails:type_name -> stores.createStoreRequest
	2,  // 6: stores.updateStoreResponse.updatedDetails:type_name -> stores.createStoreResponse
	0,  // 7: stores.viewParticularStoreResponse.foods:type_name -> stores.food
	0,  // 8: stores.getItemDetailsResponse.details:type_name -> stores.food
	1,  // 9: stores.storesService.CreateStore:input_type -> stores.createStoreRequest
	3,  // 10: stores.storesService.explore:input_type -> stores.exploreOutletsRequest
	5,  // 11: stores.storesService.OrderFood:input_type -> stores.orderFoodRequest
	13, // 12: stores.storesService.UpdateStoreDetails:input_type -> stores.updateStoreRequest
	11, // 13: stores.storesService.UpdateItemDetail:input_type -> stores.updateItemRequest
	9,  // 14: stores.storesService.FilterDish:input_type -> stores.filterFoodRequest
	7,  // 15: stores.storesService.NewItem:input_type -> stores.addItemsInStoreRequest
	17, // 16: stores.storesService.DeleteItem:input_type -> stores.deleteItemRequest
	15, // 17: stores.storesService.deleteStore:input_type -> stores.deleteStoreRequest
	19, // 18: stores.storesService.ViewItemOfStore:input_type -> stores.viewParticularStoreRequest
	21, // 19: stores.storesService.GetItemDetail:input_type -> stores.getItemDetailsRequest
	23, // 20: stores.storesService.Checkout:input_type -> stores.checkOutRequest
	2,  // 21: stores.storesService.CreateStore:output_type -> stores.createStoreResponse
	4,  // 22: stores.storesService.explore:output_type -> stores.exporeOutletsResponse
	6,  // 23: stores.storesService.OrderFood:output_type -> stores.orderFoodRespomse
	14, // 24: stores.storesService.UpdateStoreDetails:output_type -> stores.updateStoreResponse
	12, // 25: stores.storesService.UpdateItemDetail:output_type -> stores.updateItemResponse
	10, // 26: stores.storesService.FilterDish:output_type -> stores.filterFoodResponse
	8,  // 27: stores.storesService.NewItem:output_type -> stores.addItemsInStoreResponse
	18, // 28: stores.storesService.DeleteItem:output_type -> stores.deleteItemResponse
	16, // 29: stores.storesService.deleteStore:output_type -> stores.deleteStoreResponse
	20, // 30: stores.storesService.ViewItemOfStore:output_type -> stores.viewParticularStoreResponse
	22, // 31: stores.storesService.GetItemDetail:output_type -> stores.getItemDetailsResponse
	24, // 32: stores.storesService.Checkout:output_type -> stores.checkOutResponse
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_stores_proto_init() }
func file_stores_proto_init() {
	if File_stores_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stores_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Food); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploreOutletsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExporeOutletsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFoodRespomse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemsInStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemsInStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterFoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterFoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewParticularStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewParticularStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stores_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckOutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stores_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stores_proto_goTypes,
		DependencyIndexes: file_stores_proto_depIdxs,
		MessageInfos:      file_stores_proto_msgTypes,
	}.Build()
	File_stores_proto = out.File
	file_stores_proto_rawDesc = nil
	file_stores_proto_goTypes = nil
	file_stores_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StoresServiceClient is the client API for StoresService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoresServiceClient interface {
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error)
	Explore(ctx context.Context, in *ExploreOutletsRequest, opts ...grpc.CallOption) (StoresService_ExploreClient, error)
	OrderFood(ctx context.Context, in *OrderFoodRequest, opts ...grpc.CallOption) (*OrderFoodRespomse, error)
	UpdateStoreDetails(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*UpdateStoreResponse, error)
	UpdateItemDetail(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error)
	FilterDish(ctx context.Context, in *FilterFoodRequest, opts ...grpc.CallOption) (StoresService_FilterDishClient, error)
	NewItem(ctx context.Context, in *AddItemsInStoreRequest, opts ...grpc.CallOption) (*AddItemsInStoreResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	ViewItemOfStore(ctx context.Context, in *ViewParticularStoreRequest, opts ...grpc.CallOption) (StoresService_ViewItemOfStoreClient, error)
	GetItemDetail(ctx context.Context, in *GetItemDetailsRequest, opts ...grpc.CallOption) (*GetItemDetailsResponse, error)
	Checkout(ctx context.Context, in *CheckOutRequest, opts ...grpc.CallOption) (*CheckOutResponse, error)
}

type storesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoresServiceClient(cc grpc.ClientConnInterface) StoresServiceClient {
	return &storesServiceClient{cc}
}

func (c *storesServiceClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	out := new(CreateStoreResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/CreateStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) Explore(ctx context.Context, in *ExploreOutletsRequest, opts ...grpc.CallOption) (StoresService_ExploreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoresService_serviceDesc.Streams[0], "/stores.storesService/explore", opts...)
	if err != nil {
		return nil, err
	}
	x := &storesServiceExploreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoresService_ExploreClient interface {
	Recv() (*ExporeOutletsResponse, error)
	grpc.ClientStream
}

type storesServiceExploreClient struct {
	grpc.ClientStream
}

func (x *storesServiceExploreClient) Recv() (*ExporeOutletsResponse, error) {
	m := new(ExporeOutletsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storesServiceClient) OrderFood(ctx context.Context, in *OrderFoodRequest, opts ...grpc.CallOption) (*OrderFoodRespomse, error) {
	out := new(OrderFoodRespomse)
	err := c.cc.Invoke(ctx, "/stores.storesService/OrderFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) UpdateStoreDetails(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*UpdateStoreResponse, error) {
	out := new(UpdateStoreResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/UpdateStoreDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) UpdateItemDetail(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error) {
	out := new(UpdateItemResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/UpdateItemDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) FilterDish(ctx context.Context, in *FilterFoodRequest, opts ...grpc.CallOption) (StoresService_FilterDishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoresService_serviceDesc.Streams[1], "/stores.storesService/FilterDish", opts...)
	if err != nil {
		return nil, err
	}
	x := &storesServiceFilterDishClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoresService_FilterDishClient interface {
	Recv() (*FilterFoodResponse, error)
	grpc.ClientStream
}

type storesServiceFilterDishClient struct {
	grpc.ClientStream
}

func (x *storesServiceFilterDishClient) Recv() (*FilterFoodResponse, error) {
	m := new(FilterFoodResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storesServiceClient) NewItem(ctx context.Context, in *AddItemsInStoreRequest, opts ...grpc.CallOption) (*AddItemsInStoreResponse, error) {
	out := new(AddItemsInStoreResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/NewItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/deleteStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) ViewItemOfStore(ctx context.Context, in *ViewParticularStoreRequest, opts ...grpc.CallOption) (StoresService_ViewItemOfStoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoresService_serviceDesc.Streams[2], "/stores.storesService/ViewItemOfStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &storesServiceViewItemOfStoreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoresService_ViewItemOfStoreClient interface {
	Recv() (*ViewParticularStoreResponse, error)
	grpc.ClientStream
}

type storesServiceViewItemOfStoreClient struct {
	grpc.ClientStream
}

func (x *storesServiceViewItemOfStoreClient) Recv() (*ViewParticularStoreResponse, error) {
	m := new(ViewParticularStoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storesServiceClient) GetItemDetail(ctx context.Context, in *GetItemDetailsRequest, opts ...grpc.CallOption) (*GetItemDetailsResponse, error) {
	out := new(GetItemDetailsResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/GetItemDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesServiceClient) Checkout(ctx context.Context, in *CheckOutRequest, opts ...grpc.CallOption) (*CheckOutResponse, error) {
	out := new(CheckOutResponse)
	err := c.cc.Invoke(ctx, "/stores.storesService/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoresServiceServer is the server API for StoresService service.
type StoresServiceServer interface {
	CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)
	Explore(*ExploreOutletsRequest, StoresService_ExploreServer) error
	OrderFood(context.Context, *OrderFoodRequest) (*OrderFoodRespomse, error)
	UpdateStoreDetails(context.Context, *UpdateStoreRequest) (*UpdateStoreResponse, error)
	UpdateItemDetail(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
	FilterDish(*FilterFoodRequest, StoresService_FilterDishServer) error
	NewItem(context.Context, *AddItemsInStoreRequest) (*AddItemsInStoreResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	ViewItemOfStore(*ViewParticularStoreRequest, StoresService_ViewItemOfStoreServer) error
	GetItemDetail(context.Context, *GetItemDetailsRequest) (*GetItemDetailsResponse, error)
	Checkout(context.Context, *CheckOutRequest) (*CheckOutResponse, error)
}

// UnimplementedStoresServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStoresServiceServer struct {
}

func (*UnimplementedStoresServiceServer) CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (*UnimplementedStoresServiceServer) Explore(*ExploreOutletsRequest, StoresService_ExploreServer) error {
	return status.Errorf(codes.Unimplemented, "method Explore not implemented")
}
func (*UnimplementedStoresServiceServer) OrderFood(context.Context, *OrderFoodRequest) (*OrderFoodRespomse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderFood not implemented")
}
func (*UnimplementedStoresServiceServer) UpdateStoreDetails(context.Context, *UpdateStoreRequest) (*UpdateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStoreDetails not implemented")
}
func (*UnimplementedStoresServiceServer) UpdateItemDetail(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItemDetail not implemented")
}
func (*UnimplementedStoresServiceServer) FilterDish(*FilterFoodRequest, StoresService_FilterDishServer) error {
	return status.Errorf(codes.Unimplemented, "method FilterDish not implemented")
}
func (*UnimplementedStoresServiceServer) NewItem(context.Context, *AddItemsInStoreRequest) (*AddItemsInStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewItem not implemented")
}
func (*UnimplementedStoresServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedStoresServiceServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (*UnimplementedStoresServiceServer) ViewItemOfStore(*ViewParticularStoreRequest, StoresService_ViewItemOfStoreServer) error {
	return status.Errorf(codes.Unimplemented, "method ViewItemOfStore not implemented")
}
func (*UnimplementedStoresServiceServer) GetItemDetail(context.Context, *GetItemDetailsRequest) (*GetItemDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemDetail not implemented")
}
func (*UnimplementedStoresServiceServer) Checkout(context.Context, *CheckOutRequest) (*CheckOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}

func RegisterStoresServiceServer(s *grpc.Server, srv StoresServiceServer) {
	s.RegisterService(&_StoresService_serviceDesc, srv)
}

func _StoresService_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/CreateStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_Explore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExploreOutletsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoresServiceServer).Explore(m, &storesServiceExploreServer{stream})
}

type StoresService_ExploreServer interface {
	Send(*ExporeOutletsResponse) error
	grpc.ServerStream
}

type storesServiceExploreServer struct {
	grpc.ServerStream
}

func (x *storesServiceExploreServer) Send(m *ExporeOutletsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoresService_OrderFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).OrderFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/OrderFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).OrderFood(ctx, req.(*OrderFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_UpdateStoreDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).UpdateStoreDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/UpdateStoreDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).UpdateStoreDetails(ctx, req.(*UpdateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_UpdateItemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).UpdateItemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/UpdateItemDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).UpdateItemDetail(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_FilterDish_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FilterFoodRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoresServiceServer).FilterDish(m, &storesServiceFilterDishServer{stream})
}

type StoresService_FilterDishServer interface {
	Send(*FilterFoodResponse) error
	grpc.ServerStream
}

type storesServiceFilterDishServer struct {
	grpc.ServerStream
}

func (x *storesServiceFilterDishServer) Send(m *FilterFoodResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoresService_NewItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddItemsInStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).NewItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/NewItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).NewItem(ctx, req.(*AddItemsInStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/DeleteStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_ViewItemOfStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ViewParticularStoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoresServiceServer).ViewItemOfStore(m, &storesServiceViewItemOfStoreServer{stream})
}

type StoresService_ViewItemOfStoreServer interface {
	Send(*ViewParticularStoreResponse) error
	grpc.ServerStream
}

type storesServiceViewItemOfStoreServer struct {
	grpc.ServerStream
}

func (x *storesServiceViewItemOfStoreServer) Send(m *ViewParticularStoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoresService_GetItemDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).GetItemDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/GetItemDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).GetItemDetail(ctx, req.(*GetItemDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoresService_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServiceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stores.storesService/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServiceServer).Checkout(ctx, req.(*CheckOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoresService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stores.storesService",
	HandlerType: (*StoresServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStore",
			Handler:    _StoresService_CreateStore_Handler,
		},
		{
			MethodName: "OrderFood",
			Handler:    _StoresService_OrderFood_Handler,
		},
		{
			MethodName: "UpdateStoreDetails",
			Handler:    _StoresService_UpdateStoreDetails_Handler,
		},
		{
			MethodName: "UpdateItemDetail",
			Handler:    _StoresService_UpdateItemDetail_Handler,
		},
		{
			MethodName: "NewItem",
			Handler:    _StoresService_NewItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _StoresService_DeleteItem_Handler,
		},
		{
			MethodName: "deleteStore",
			Handler:    _StoresService_DeleteStore_Handler,
		},
		{
			MethodName: "GetItemDetail",
			Handler:    _StoresService_GetItemDetail_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _StoresService_Checkout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "explore",
			Handler:       _StoresService_Explore_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FilterDish",
			Handler:       _StoresService_FilterDish_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ViewItemOfStore",
			Handler:       _StoresService_ViewItemOfStore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stores.proto",
}
